// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzbWebDAV.Database;

#nullable disable

namespace NzbWebDAV.Database.Migrations
{
    [DbContext(typeof(DavDatabaseContext))]
    partial class DavDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
            modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NzbWebDAV.Database.Models.Account", b =>
                {
                    b.Property<int>("Type");

                    b.Property<string>("Username")
                        .HasMaxLength(255);

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("RandomSalt")
                        .IsRequired();

                    b.HasKey("Type", "Username");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ArrDownloadCorrelation", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int?>("AlbumId");

                    b.Property<string>("ArrApp")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Category")
                        .HasMaxLength(255);

                    b.Property<string>("CustomFormatsJson");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DownloadClient")
                        .HasMaxLength(255);

                    b.Property<string>("DownloadId")
                        .HasMaxLength(255);

                    b.Property<int?>("EpisodeId");

                    b.Property<string>("EpisodeIdsJson");

                    b.Property<Guid?>("HistoryItemId");

                    b.Property<string>("Indexer")
                        .HasMaxLength(255);

                    b.Property<string>("InstanceHost")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<int?>("ArtistId");

                    b.Property<bool>("IsDuplicate");

                    b.Property<bool>("IsUpgrade");

                    b.Property<long>("LastSeenAt");

                    b.Property<bool>("ManualLock");

                    b.Property<string>("MediaKey")
                        .HasMaxLength(255);

                    b.Property<int?>("MovieId");

                    b.Property<string>("Quality")
                        .HasMaxLength(255);

                    b.Property<Guid?>("QueueItemId");

                    b.Property<int?>("QueueRecordId");

                    b.Property<string>("ReleaseTitle")
                        .HasMaxLength(1024);

                    b.Property<int?>("SeasonNumber");

                    b.Property<int?>("SeriesId");

                    b.Property<string>("Status")
                        .HasMaxLength(64);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("TrackedDownloadState")
                        .HasMaxLength(64);

                    b.Property<string>("TrackedDownloadStatus")
                        .HasMaxLength(64);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("HistoryItemId");

                    b.HasIndex("QueueItemId");

                    b.HasIndex("IsDuplicate", "LastSeenAt");

                    b.HasIndex("Source", "ManualLock");

                    b.HasIndex("ArrApp", "InstanceKey", "DownloadId");

                    b.HasIndex("ArrApp", "InstanceKey", "MediaKey");

                    b.HasIndex("ArrApp", "InstanceKey", "QueueRecordId");

                    b.ToTable("ArrDownloadCorrelations", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ArrDownloadLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ArrApp")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DownloadId")
                        .HasMaxLength(255);

                    b.Property<Guid?>("HistoryItemId");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("MediaKey")
                        .HasMaxLength(255);

                    b.Property<Guid?>("QueueItemId");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StateReason")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.HasIndex("HistoryItemId", "CreatedAt");

                    b.HasIndex("QueueItemId", "CreatedAt");

                    b.HasIndex("ArrApp", "InstanceKey", "State", "CreatedAt");

                    b.ToTable("ArrDownloadLifecycleEvents", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ArrSearchNudgeCommand", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ArrApp")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int?>("CommandId");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<long?>("CompletedAt");

                    b.Property<string>("CooldownKey")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("Error")
                        .HasMaxLength(1024);

                    b.Property<string>("InstanceHost")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long>("NextAllowedAt");

                    b.Property<string>("ReasonsJson")
                        .IsRequired();

                    b.Property<int>("Score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("TargetsJson")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CooldownKey", "NextAllowedAt");

                    b.HasIndex("ArrApp", "InstanceKey", "Status", "CreatedAt");

                    b.ToTable("ArrSearchNudgeCommands", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.BlobCleanupItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.HasKey("Id");

                    b.ToTable("BlobCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ConfigItem", b =>
                {
                    b.Property<string>("ConfigName");

                    b.Property<string>("ConfigValue")
                        .IsRequired();

                    b.HasKey("ConfigName");

                    b.ToTable("ConfigItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavCleanupItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.HasKey("Id");

                    b.ToTable("DavCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("FileBlobId");

                    b.Property<long?>("FileSize");

                    b.Property<Guid?>("HistoryItemId");

                    b.Property<string>("IdPrefix")
                        .IsRequired();

                    b.Property<long?>("LastHealthCheck");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<long?>("NextHealthCheck");

                    b.Property<Guid?>("NzbBlobId");

                    b.Property<Guid?>("ParentId");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<long?>("ReleaseDate");

                    b.Property<int>("SubType");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("NzbBlobId");

                    b.HasIndex("IdPrefix", "Type");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.HasIndex("HistoryItemId", "SubType", "CreatedAt");

                    b.HasIndex("HistoryItemId", "Type", "CreatedAt");

                    b.HasIndex("Type", "HistoryItemId", "NextHealthCheck", "ReleaseDate", "Id");

                    b.ToTable("DavItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Metadata")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DavMultipartFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("SegmentIds")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DavNzbFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("RarParts")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DavRarFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckResult", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<Guid>("DavItemId");

                    b.Property<string>("Message");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<int>("RepairStatus");

                    b.Property<int>("Result");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DavItemId", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("DavItemId")
                        .HasFilter("\"RepairStatus\" = 3");

                    b.HasIndex("Result", "RepairStatus", "CreatedAt");

                    b.ToTable("HealthCheckResults", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckStat", b =>
                {
                    b.Property<long>("DateStartInclusive");

                    b.Property<long>("DateEndExclusive");

                    b.Property<int>("Result");

                    b.Property<int>("RepairStatus");

                    b.Property<int>("Count");

                    b.HasKey("DateStartInclusive", "DateEndExclusive", "Result", "RepairStatus");

                    b.ToTable("HealthCheckStats", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HistoryCleanupItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("DeleteMountedFiles");

                    b.HasKey("Id");

                    b.ToTable("HistoryCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HistoryItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("DownloadDirId");

                    b.Property<int>("DownloadStatus");

                    b.Property<int>("DownloadTimeSeconds");

                    b.Property<string>("FailMessage");

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<string>("JobName")
                        .IsRequired();

                    b.Property<Guid?>("NzbBlobId");

                    b.Property<long>("TotalSegmentBytes");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NzbBlobId");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("Category", "DownloadDirId");

                    b.ToTable("HistoryItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NzbBlobCleanupItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.HasKey("Id");

                    b.ToTable("NzbBlobCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ImportReceipt", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<Guid>("DavItemId");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024);

                    b.Property<Guid>("HistoryItemId");

                    b.Property<long?>("ImportedAt");

                    b.Property<long?>("RemovedAt");

                    b.Property<int>("State");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("DavItemId", "HistoryItemId")
                        .IsUnique();

                    b.ToTable("ImportReceipts", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NzbName", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("NzbNames", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RcloneInvalidationItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("Attempts");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024);

                    b.Property<long?>("LastAttemptAt");

                    b.Property<long>("NextAttemptAt");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("NextAttemptAt", "CreatedAt");

                    b.ToTable("RcloneInvalidationItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairBrokenFile", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("Cleared");

                    b.Property<long>("CreatedAt");

                    b.Property<Guid>("DavItemId");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<Guid>("RepairRunId");

                    b.HasKey("Id");

                    b.HasIndex("DavItemId", "Cleared");

                    b.HasIndex("RepairRunId", "Cleared", "CreatedAt");

                    b.ToTable("RepairBrokenFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairEntryHealth", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<Guid>("DavItemId");

                    b.Property<string>("Message")
                        .HasMaxLength(1024);

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<Guid>("RepairRunId");

                    b.Property<int>("State");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("RepairRunId", "DavItemId")
                        .IsUnique();

                    b.HasIndex("RepairRunId", "State", "UpdatedAt");

                    b.ToTable("RepairEntryHealth", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairRun", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("ActionNeeded");

                    b.Property<int>("BrokenFiles");

                    b.Property<long?>("CancelledAt");

                    b.Property<int>("Checked");

                    b.Property<long?>("CompletedAt");

                    b.Property<int>("Deleted");

                    b.Property<string>("Message")
                        .HasMaxLength(1024);

                    b.Property<int>("Missing");

                    b.Property<long?>("NextDueAt");

                    b.Property<int>("ProviderErrors");

                    b.Property<int>("Repaired");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<long>("StartedAt");

                    b.Property<int>("Status");

                    b.Property<int>("Total");

                    b.Property<int>("Unknown");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAt");

                    b.ToTable("RepairRuns", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueuePriorityHint", b =>
                {
                    b.Property<Guid>("QueueItemId");

                    b.Property<bool>("ApplyToScheduling");

                    b.Property<long>("ComputedAt");

                    b.Property<int>("EffectivePriority");

                    b.Property<long>("ExpiresAt");

                    b.Property<string>("ReasonsJson")
                        .IsRequired();

                    b.Property<int>("Score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StaleReason")
                        .HasMaxLength(1024);

                    b.HasKey("QueueItemId");

                    b.HasIndex("EffectivePriority", "Score", "ExpiresAt");

                    b.ToTable("QueuePriorityHints", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueItem", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ArchivePassword");

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<string>("JobName")
                        .IsRequired();

                    b.Property<long>("NzbFileSize");

                    b.Property<DateTime?>("PauseUntil");

                    b.Property<int>("PostProcessing");

                    b.Property<int>("Priority");

                    b.Property<long>("TotalSegmentBytes");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("Category", "FileName")
                        .IsUnique();

                    b.HasIndex("Priority", "CreatedAt");

                    b.HasIndex("Priority", "PauseUntil", "CreatedAt");

                    b.HasIndex("Category", "Priority", "CreatedAt");

                    b.ToTable("QueueItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("NzbContents")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("QueueNzbContents", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.WorkerJob", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("Attempts");

                    b.Property<long>("AvailableAt");

                    b.Property<long?>("CancelRequestedAt");

                    b.Property<long?>("CompletedAt");

                    b.Property<long>("CreatedAt");

                    b.Property<int>("Kind");

                    b.Property<int?>("FailureKind");

                    b.Property<long?>("LastHeartbeatAt");

                    b.Property<long?>("LeaseExpiresAt");

                    b.Property<long>("LeaseGeneration")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0L);

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(255);

                    b.Property<Guid?>("LeaseToken");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024);

                    b.Property<string>("PayloadJson");

                    b.Property<int>("Priority");

                    b.Property<string>("ProgressJson")
                        .HasMaxLength(16384);

                    b.Property<long?>("ProgressUpdatedAt");

                    b.Property<string>("ResultJson")
                        .HasMaxLength(16384);

                    b.Property<long?>("StartedAt");

                    b.Property<int>("Status");

                    b.Property<Guid>("TargetId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "TargetId")
                        .IsUnique();

                    b.HasIndex("Kind", "Status", "AvailableAt", "LeaseExpiresAt", "Priority", "CreatedAt");

                    b.HasIndex("Kind", "Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_WorkerJobs_Kind_Status_LeaseExpiresAt");

                    b.HasIndex("Kind", "Status", "Priority", "AvailableAt", "CreatedAt")
                        .IsDescending(false, false, true, false, false)
                        .HasDatabaseName("IX_WorkerJobs_Kind_Status_Priority_AvailableAt_CreatedAt");

                    b.HasIndex("Status", "LeaseExpiresAt", "LeaseGeneration")
                        .HasDatabaseName("IX_WorkerJobs_Status_LeaseExpiresAt_LeaseGeneration");

                    b.ToTable("WorkerJobs", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavMultipartFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavNzbFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavRarFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.QueueItem", "QueueItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.QueueNzbContents", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueuePriorityHint", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.QueueItem", null)
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.QueuePriorityHint", "QueueItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairBrokenFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.RepairRun", null)
                        .WithMany()
                        .HasForeignKey("RepairRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairEntryHealth", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.RepairRun", null)
                        .WithMany()
                        .HasForeignKey("RepairRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
