// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzbWebDAV.Database;

#nullable disable

namespace NzbWebDAV.Database.Migrations
{
    [DbContext(typeof(DavDatabaseContext))]
    partial class DavDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("NzbWebDAV.Database.Models.Account", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RandomSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type", "Username");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.BlobCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlobCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ConfigItem", b =>
                {
                    b.Property<string>("ConfigName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigName");

                    b.ToTable("ConfigItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileBlobId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("HistoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastHealthCheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextHealthCheck")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NzbBlobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReleaseDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NzbBlobId");

                    b.HasIndex("IdPrefix", "Type");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.HasIndex("HistoryItemId", "SubType", "CreatedAt");

                    b.HasIndex("HistoryItemId", "Type", "CreatedAt");

                    b.HasIndex("Type", "HistoryItemId", "NextHealthCheck", "ReleaseDate", "Id");

                    b.ToTable("DavItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavMultipartFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavNzbFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RarParts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavRarFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DavItemId")
                        .HasFilter("\"RepairStatus\" = 3");

                    b.HasIndex("Result", "RepairStatus", "CreatedAt");

                    b.ToTable("HealthCheckResults", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckStat", b =>
                {
                    b.Property<long>("DateStartInclusive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DateEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("DateStartInclusive", "DateEndExclusive", "Result", "RepairStatus");

                    b.ToTable("HealthCheckStats", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HistoryCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteMountedFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HistoryCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HistoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadDirId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NzbBlobId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSegmentBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NzbBlobId");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("Category", "DownloadDirId");

                    b.ToTable("HistoryItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NzbBlobCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NzbBlobCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NzbName", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NzbNames", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RcloneInvalidationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("NextAttemptAt", "CreatedAt");

                    b.ToTable("RcloneInvalidationItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairBrokenFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cleared")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepairRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DavItemId", "Cleared");

                    b.HasIndex("RepairRunId", "Cleared", "CreatedAt");

                    b.ToTable("RepairBrokenFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairEntryHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepairRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepairRunId", "DavItemId")
                        .IsUnique();

                    b.HasIndex("RepairRunId", "State", "UpdatedAt");

                    b.ToTable("RepairEntryHealth", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrokenFiles")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CancelledAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Missing")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextDueAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderErrors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repaired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unknown")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAt");

                    b.ToTable("RepairRuns", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivePassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NzbFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSegmentBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("Category", "FileName")
                        .IsUnique();

                    b.HasIndex("Priority", "CreatedAt");

                    b.HasIndex("Priority", "PauseUntil", "CreatedAt");

                    b.HasIndex("Category", "Priority", "CreatedAt");

                    b.ToTable("QueueItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("NzbContents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QueueNzbContents", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.WorkerJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AvailableAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "TargetId")
                        .IsUnique();

                    b.HasIndex("Kind", "Status", "AvailableAt", "LeaseExpiresAt", "Priority", "CreatedAt");

                    b.ToTable("WorkerJobs", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavMultipartFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavNzbFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavRarFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.QueueItem", "QueueItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.QueueNzbContents", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairBrokenFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.RepairRun", null)
                        .WithMany()
                        .HasForeignKey("RepairRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.RepairEntryHealth", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.RepairRun", null)
                        .WithMany()
                        .HasForeignKey("RepairRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
