name: "Verify Branches"

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
